//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveRequestDate
    {
        public int ID { get; set; }
        public System.Guid EmployeeLeaveRequestID { get; set; }
        public System.DateTime Day { get; set; }
        public bool IsFullDay { get; set; }
    
        public virtual EmployeeLeaveRequest EmployeeLeaveRequest { get; set; }
    }
}
