//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeLeaveManualAllotments = new HashSet<EmployeeLeaveManualAllotment>();
            this.EmployeeLeaveManualAllotments1 = new HashSet<EmployeeLeaveManualAllotment>();
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
            this.EmployeeLeaveRequestStatusChanges = new HashSet<EmployeeLeaveRequestStatusChanx>();
            this.Subordinates = new HashSet<Employee>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public byte[] Salt { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.Guid> SupervisorID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNumber { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ICollection<EmployeeLeaveManualAllotment> EmployeeLeaveManualAllotments { get; set; }
        public virtual ICollection<EmployeeLeaveManualAllotment> EmployeeLeaveManualAllotments1 { get; set; }
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
        public virtual ICollection<EmployeeLeaveRequestStatusChanx> EmployeeLeaveRequestStatusChanges { get; set; }
        public virtual ICollection<Employee> Subordinates { get; set; }
        public virtual Employee Supervisor { get; set; }
    }
}
