//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveRequestStatusChanx
    {
        public int ID { get; set; }
        public System.Guid EmployeeLeaveRequestID { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.Guid ChangedByEmployeeID { get; set; }
        public int LeaveStatusID { get; set; }
        public string Reason { get; set; }
    
        public virtual EmployeeLeaveRequest EmployeeLeaveRequest { get; set; }
        public virtual Employee ChangedByEmployee { get; set; }
        public virtual LeaveStatus LeaveStatus { get; set; }
    }
}
