//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
            this.EmployeeLeaveManualAllotments = new HashSet<EmployeeLeaveManualAllotment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int YearlyLeave { get; set; }
        public bool IsInheritable { get; set; }
    
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
        public virtual ICollection<EmployeeLeaveManualAllotment> EmployeeLeaveManualAllotments { get; set; }
    }
}
